oper<-"http://companyinfo.stock.naver.com/v1/company/ajax/cF1001.aspx?cmp_cd="
code<-"028150"
oper1<-oper%>%paste(code,"fin_typ=0&freq_typ=Y",sep="")
oper_table<-html_table(read_html(oper1)%>%html_nodes(".gHead01.all-width"),fill=T)[[1]]
str(oper_table)
head(oper_table)
colnames(oper_table)<-c(colnames(oper_table)[1],str_sub(oper_table[1,2:9],1,7))
rownames(oper_table)<-oper_table[,1]
dim(oper_table)
new_table<-as.data.frame(oper_table[2:33,2:9])
str(new_table)
for(i in 1:8) new_table[,i]<-as.numeric(gsub(",","",new_table[,i]))
apply(new_table,1,summary)
fs<-t(new_table)
bis<-fs[,9]/fs[,7]
sp<-fs[,25]*fs[,26]
fs<-cbind(fs,bis)
fs<-cbind(fs,sp)
fs
nfs<-fs[1:5,-c(5,6,10,11,12,18,25:32)]
nfs
#install.packages("corrplot")
library("corrplot")
round(cor(nfs[,-25]),3)
corrplot(cor(nfs[,-25]))
nnfs<-as.data.frame(nfs)
str(nnfs)
nnfs
model<-lm(sp~.,nnfs)
summary(model)
anova(model)
