#재무제표
oper<-"http://companyinfo.stock.naver.com/v1/company/ajax/cF1001.aspx?cmp_cd="
code<-"028150"
oper1<-oper%>%paste(code,"fin_typ=0&freq_typ=Y",sep="")
oper_table<-html_table(read_html(oper1)%>%html_nodes(".gHead01.all-width"),fill=T)[[1]]
str(oper_table)
head(oper_table)
colnames(oper_table)<-c(colnames(oper_table)[1],str_sub(oper_table[1,2:9],1,7))
rownames(oper_table)<-oper_table[,1]
dim(oper_table)
new_table<-as.data.frame(oper_table[2:33,2:9])
str(new_table)
for(i in 1:8) new_table[,i]<-as.numeric(gsub(",","",new_table[,i]))
apply(new_table,1,summary)
fs<-t(new_table)
bis<-fs[,9]/fs[,7]
sp<-fs[,25]*fs[,26]
fs<-cbind(fs,bis)
fs<-cbind(fs,sp)
fs
nfs<-fs[1:5,-c(5,6,10,11,12:16,18,25:26,32)]
nfs
colnames(nfs)<-letters[1:21]
nfs
nfs<-transform(nfs,a_s=scale(a),b_s=scale(b),c_s=scale(c),d_s=scale(d),e_s=scale(e),f_s=scale(f)
,g_s=scale(g),h_s=scale(h),i_s=scale(i),j_s=scale(j),k_s=scale(k),l_s=scale(l)
,m_s=scale(m),n_s=scale(n),o_s=scale(o),p_s=scale(p),q_s=scale(q),r_s=scale(r)
,s_s=scale(s),t_s=scale(t))
nfs<-nfs[,21:41]
nfs
#nfs<-transform(nfs,f_s2=max(f_s)-f_s,k_s2=max(k_s)-k_s,q_s2=max(q_s)-q_s)
#nfs<-nfs[,-c(6,11,17)]
bartlett.test(nfs)
cor(nfs[,-1])
round(cor(nfs[,-1]),digits=3)
plot(nfs[,-1])
pnfs<-prcomp(nfs[,-1])
summary(pnfs)
print(pnfs)
plot(pnfs,type="l",sub="Scree Plot")
lpnfs<-lm(nfs[,1]~pnfs$x[,1]+pnfs$x[,2])
summary(lpnfs)
